### PR TITLE
IBM Cloud Tools (ICT) deployment-ready updates

### PR DESCRIPTION
**Pull request by egross91**
After reaching out to @l2fprod about having this app featured in ICT, I have made the necessary changes to make this app deployment-ready via ICT.

**NOTE:** This has been tested with ICT's [GitHub deployment](https://developer.ibm.com/bluemix/2016/09/07/custom-github-samples-ibm-cloud-tools-swift/) flow via my fork.

### CODE REVIEW

**Comment by rvennam** [comment]
@egross91 thoughts on having ICT asking the user to run a build before doing the deployment to avoid delivering war? Or invoking maven directly? java devs should have maven already.

**Comment by l2fprod** [comment]
@egross91 

I agree with @rvennam on invoking maven from ICT.

We can't have the war file committed in the repo. It should be rebuilt by the tool. Having this binary in GIT would be error prone. It means everytime someone changes the code they should commit the .war. It is not an acceptable solution.

Also the aim of this tutorial is really to go through the manual steps of setting up your environment for local development, shipping a precompiled .war does not support this goal.

**Comment by egross91** [comment]
@rvennam @l2fprod Hey! Sorry, I just saw these. I never got the response notifications in my email.

As much as it would be ideal for ICT to build the project for the user to generate a .war, I'm not sure how feasible that will be considering that we would be making the assumption that everyone who clones or creates the project from ICT will have Maven installed to build the project. 

An alternative could be to have Maven listed as a Local Dev Requirement in ICT, but that still doesn't address the problem of having ICT building the project for them. As a supplement, mentioning that the project needs to be built locally before development as a Step-by-Step Instruction in ICT. Or briefly mentioning Maven and just referring to the README on GitHub would suffice too. This is also a section in ICT for our users to view before cloning and deploying the project.

**Comment by rvennam** [comment]
I think its safe to assume java devs have maven. If not, they wouldn't get very far with the sample regardless of ICT. If ICT runs maven for you, it'll need to ask the user which goal(s) they want to run. It can get messy fast. If you're keen on having this part of ICT, then having the user run the build independently would be easiest way to go. The goal of this repo was to teach the user how to set up a local liberty instance - maybe this repo isn't the right choice.

**Comment by egross91** [comment]
Trying to incorporate that much functionality just to support Maven in ICT with a short amount of time before Interconnect probably won't be the wisest decision. But I do think that the idea of getting the developer to setup up a local Liberty instance on their own is ok for the time being. Not all of the projects that are in ICT are just a simple clone & deploy sequence of steps.

I do agree, this probably isn't the best choice. Unfortunately, I don't think there's an adequate amount of time left to search for another candidate, ask if they would like to be featured, then work with the individual(s) to get the necessary copy and designs finished before the end of our release.

**Comment by egross91** [comment]
@rvennam @l2fprod 

To wrap up this discussion, I still want to feature this app, as well as @rvennam's apps for the next release of ICT. Pushing a `.war` (or any binary files for that matter) is a poor decision. I figured it would make the process a little easier for our users, but that would take away from the purpose of the projects. 

If you two could mention in Step 12 of the [app submission form](http://www.surveygizmo.com/s3/3171731/Test-ICT-Sample-App-Form) that the Java projects will require the installation of Maven and the project to be built locally before deployment. Also mentioning that the GitHub repo has the steps outlined for them. That way users are aware of the little extra steps that will be needed and have a resource to follow along with.

**EDIT:** Closed the PR because these are bad changes.

**Pull request closed without merging**
